export function generateReadme(
  projectName: string,
  architecture: string,
  variant: string,
  packageManager: string,
  hasLinting: boolean,
): string {
  const startCommand =
    packageManager === "yarn" ? "yarn dev" : `${packageManager} dev`;
  const lintCommand =
    packageManager === "yarn" ? "yarn lint" : `${packageManager} run lint`;
  const buildCommand =
    packageManager === "yarn" ? "yarn build" : `${packageManager} run build`;

  return `# ${projectName}

A Next.js project created with [Heildamm](https://github.com/glatztp/create-heildamm).

## Architecture

This project uses the **${architecture}** architecture with the **${variant}** variant.

### Architecture Overview

The ${architecture} architecture provides:
- ${getArchitectureDescription(architecture)}

### Technology Stack

- **Framework**: Next.js 14+
- **Runtime**: Node.js${variant === "trpc" ? "\n- **API**: tRPC" : ""}${variant === "prisma" || variant === "full" ? "\n- **Database**: Prisma ORM" : ""}${hasLinting ? "\n- **Linting**: ESLint + Prettier" : ""}
- **Package Manager**: ${packageManager}

## Getting Started

### Prerequisites

- Node.js 18+ installed
- ${packageManager} installed

### Installation

\`\`\`bash
# Install dependencies
${packageManager} install

# Start development server
${startCommand}
\`\`\`

The application will be available at [http://localhost:3000](http://localhost:3000).

## Available Scripts

\`\`\`bash
# Development server
${startCommand}

# Build for production
${buildCommand}

# Start production server
${packageManager === "yarn" ? "yarn start" : `${packageManager} start`}

${
  hasLinting
    ? `# Run linting
${lintCommand}

# Fix linting issues
${packageManager === "yarn" ? "yarn lint:fix" : `${packageManager} run lint:fix`}
`
    : ""
}
\`\`\`

## Project Structure

The project follows the **${architecture}** pattern:

${getProjectStructureGuide(architecture)}

## Configuration Files

- \`next.config.ts\` - Next.js configuration
- \`tsconfig.json\` - TypeScript configuration${variant === "prisma" || variant === "full" ? "\n- \`prisma/schema.prisma\` - Database schema" : ""}${hasLinting ? "\n- \`.eslintrc.json\` - ESLint configuration\n- \`.prettierrc\` - Prettier configuration" : ""}

## Learn More

- [Next.js Documentation](https://nextjs.org/docs)
- [React Documentation](https://react.dev)${variant === "trpc" ? "\n- [tRPC Documentation](https://trpc.io)" : ""}${variant === "prisma" || variant === "full" ? "\n- [Prisma Documentation](https://www.prisma.io/docs)" : ""}

## License

This project is open source and available under the MIT license.

## Contributing

Contributions are welcome! Please feel free to submit a Pull Request.

---

Generated by [Heildamm](https://github.com/glatztp/create-heildamm)
`;
}

function getArchitectureDescription(architecture: string): string {
  const descriptions: Record<string, string> = {
    "feature-based":
      "organizing code around business features, making it easier to maintain and scale",
    "layer-based":
      "separating concerns into presentation, API, business logic, and data layers",
    "domain-driven":
      "organizing code around business domains with clear boundaries and responsibilities",
    monorepo:
      "managing multiple applications and packages in a single repository for shared code",
  };
  return descriptions[architecture] || "custom architecture pattern";
}

function getProjectStructureGuide(architecture: string): string {
  const guides: Record<string, string> = {
    "feature-based": `
\`\`\`
src/
├── features/           # Feature modules
│   ├── auth/
│   ├── dashboard/
│   └── profile/
├── components/         # Shared components
├── app.tsx            # App shell
└── layout.tsx         # Root layout
\`\`\`
`,
    "layer-based": `
\`\`\`
src/
├── presentation/      # UI components and pages
├── api/               # API routes
├── logic/             # Business logic
└── data/              # Data access layer
\`\`\`
`,
    "domain-driven": `
\`\`\`
src/
├── domains/           # Domain modules
│   ├── users/
│   ├── products/
│   └── orders/
├── components/        # Shared components
└── app.tsx
\`\`\`
`,
    monorepo: `
\`\`\`
apps/
├── web/               # Web application
└── api/               # API server
packages/
├── ui/                # Shared UI components
├── types/             # Shared types
└── utils/             # Shared utilities
\`\`\`
`,
  };
  return guides[architecture] || "Custom structure";
}
